# Import packages.
import numpy as np
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)
goback = np.random.randint(4)
print (goback)

